preprocessing:
  random_state: 42
  test_size: 0.2

training:
  time_budget_seconds: 120
  metric: "f1"
  task: "classification"
  estimators:
    - "lgbm"
    - "xgboost"
    - "rf"
    - "extra_tree"
    - "lrl1"
  n_splits: 5
  seed: 42
